general {
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on screen after sleep
}

listener {
    timeout = 30                                # 30 sek
    on-timeout = hyprctl dispatch dpms off      # screen off
    on-resume = hyprctl dispatch dpms on        # screen on
}
